### PR TITLE
hydro models => add support for setting/getting circulation pump 

### PR DESCRIPTION
**Pull request by Robbe-B**
hydro models => add support for setting/getting the minimum temperature for which the circulation pump should turn on

image

### CODE REVIEW

**Comment by Robbe-B** [comment]
@ggerrd, 
Can you check if getting and setting the value for the circulation pump works for your M1 Hydro model ? (discussed in https://github.com/Robbe-B/maestro_mcz/issues/130)

@RickType
Can you check if getting and setting the value for the circulation pump works for your M2 Hydro model ?

**Comment by RickType** [comment]
Hey, I downloaded the latest repo 0.6.0, but I can’t find this entity?

**Comment by Robbe-B** [comment]
@RickType, indeed It isn't released yet, I'll create a release for you, in order to test.

**Comment by ggerrd** [comment]
﻿Sorry I‘m didin‘t understand how get the Test file on my System But if its work it will be a big step for ne Thanks Mit freundlichen GrüßenGerd Neuhaus Gekürzte Signatur / Mobilemail Mit freundlichen GrüßenGerd Neuhaus Gekürzte Signatur / Mobilemail Am 10.12.2024 um 07:58 schrieb Robbe-B ***@***.***>:﻿
Merged #164 into main.

**Comment by Robbe-B** [comment]
@ggerrd, 
The rest of the requested features are coming soon.

**Comment by RickType** [comment]
Perfekt, will check today...Am 10.12.2024 08:29 schrieb Robbe-B ***@***.***>:
@RickType,
https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.6.1-beta is now available

**Comment by RickType** [comment]
Works perfectly, thx!Am 10.12.2024 11:39 schrieb ***@***.***:Perfekt, will check today...Am 10.12.2024 08:29 schrieb Robbe-B ***@***.***>:
@RickType,
https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.6.1-beta is now available

**Comment by Robbe-B** [comment]
@RickType, 
Great to hear !
I'm planning to implement a couple of other hydro features soon.
It would be great if you could keep verifying those for me, since I don't have any hydro model myself to test with and your setup seems to have a very complete set of hydro features.
Kind regards,
Robbe

**Comment by ggerrd** [comment]
﻿Hy Now i can See the slider Slide to a new valueBut it takes no Effekt In mqtt there came  no new temperature tooBut in mqtt it will be the original temp vorm the stove And I can See it in mqtt if I change in the App But fange from mqtt to stove do Not work at the Moment Mit freundlichen GrüßenGerd Neuhaus Gekürzte Signatur / Mobilemail Am 10.12.2024 um 11:40 schrieb RickType ***@***.***>:﻿
Perfekt, will check today...Am 10.12.2024 08:29 schrieb Robbe-B ***@***.***>:

@RickType,

https://github.com/Robbe-B/maestro_mcz/releases/tag/v0.6.1-beta is now available

**Comment by ggerrd** [comment]
My Setup is an MCZ M1 this will be the big diference, 

In the App you have to log in with Passwort ( 0434 ) to get into the Menu to Edit the Pump temp

**Comment by RickType** [comment]
That’s the same with the M2. Advanced settings and then recipes….

**Comment by Robbe-B** [comment]
@ggerrd, 
It's very odd that the SET is not working tbh. 
[Important] => Can you provide me with your diagnostics file ? (can be downloaded in this integration)
[Important] => Do you see anything in the Home Assistant logging related to the MCZ integration ? (after trying to set the circulation pump temp)

Also just for your information this integration has nothing to do with MQTT 😄 

Kind regards,
Robbe

**Comment by Robbe-B** [comment]
@ggerrd, 
Also, are you sure the SET doesn't work, couldn't it just be that the values don't update instantly (30sec polling time)
Kind Regards,
Robbe

**Comment by ggerrd** [comment]
i m sure the set doesen´t work 
if I use the slider example 60G Degree the slider get the new position and stay there all the time the value right stay all the time at 48 Degree 
threre is noch efeckt after 30sec or  minute 
at the mobile phone I have see a info like  can´t set new temp time out. but the massing was only one time and I can´t get it a second time to send a sreencout

**Comment by Robbe-B** [comment]
@ggerrd,
This is logging from another integration, not this one.

**Comment by Robbe-B** [comment]
@ggerrd, 
The logging you gave came from => https://github.com/Chibald/maestrogateway

**Comment by ggerrd** [comment]
Die Aktion number/set_value konnte nicht ausgeführt werden. unknown error

**Comment by Robbe-B** [comment]
> Die Aktion number/set_value konnte nicht ausgeführt werden. unknown error

It's good that you have a message like this, this means there is more information in the logging.
Settings => System => Logs

**Comment by ggerrd** [comment]
[home-assistant_2024-12-11T10-05-43.055Z.log](https://github.com/user-attachments/files/18093309/home-assistant_2024-12-11T10-05-43.055Z.log)

**Comment by Robbe-B** [comment]
@ggerrd, 
Unfortunately there is nothing in this logging related to this issue.

**Comment by Robbe-B** [comment]
@ggerrd, 
Does a hydro stove also has special 'modes' where certain tings cannot be set if the mode isn't active ? 
Is your Stove on while trying to set this value ?

**Comment by ggerrd** [comment]
Tempertur min for circle can set all the time in the app ( after passwort) 

i have re install and restart every thing now the stove get the new value, only the value right to the slider stay at the old value

**Comment by ggerrd** [comment]
Yes I thing it is on the right way, 
I will test it in the next hours 
Home Assistent ist my second System like a gatway too the main Server ( IPSymcon) 
all Home Assist Entitäten goes to Mqtt and by this way linked the two systems 
mybee it is posibility to set the new value by mqtt ? at the moment the pumping value does not chance 

I read 114 if you like you can get on my stove so i need your mail address too setup a login

**Comment by RickType** [comment]
Hi Robbe,

the power of the pump in percent would be also interesting.
The quality of the pellets varies. The better the wood, the higher the power in percentage. E.g. The boiler temp is 66 degree, but the pump power is higher the better the calorific value is. I know, depends also on other factors like return temperature (I have 45 degree). But still, the pump power is an interesting value.

Thx
Hotte

**Comment by RickType** [comment]
Bildschirmfoto 2024-12-16 um 07 53 31

Hi,

go a strange behaviour from the stove. See attached picture. Will restart  HA and the stove and will double check.

Don't know if there is an issue with the cloud, but it appears since I updated to the new Version.

Cheers
Hotte
 
[home-assistant_2024-12-16T06-56-29.733Z.log](https://github.com/user-attachments/files/18146072/home-assistant_2024-12-16T06-56-29.733Z.log)
[config_entry-maestro_mcz-9e621916f330ef9b684ebb1bca29a701-3.json](https://github.com/user-attachments/files/18146073/config_entry-maestro_mcz-9e621916f330ef9b684ebb1bca29a701-3.json)

**Comment by Robbe-B** [comment]
@RickType, 
I'm aware of it, it's the MCZ cloud or firmware update.
All stoves are going nuts

**Comment by Robbe-B** [comment]
@RickType, 
Did you do a firmware update ?

**Comment by RickType** [comment]
> @RickType, Did you do a firmware update ?

Nope , there was no update availble…

**Comment by RickType** [comment]
Issue seems to be solved. But it had no impact on my side. Since the MCZ cloud is not reliable, I switched back to local steering. Basically I use the dry contact of a Shelly to switch the stove on…

**Comment by ggerrd** [comment]
hey, I've been testing it intensively over the last few days. The communication with the oven works very well. The display and the slider only update occasionally for me Since I set the value via automation anyway, it doesn't bother me Thank you happy holidays

**Pull request merged**
